version: '1'

services:
  main-app:
    build: ./apps/main-app
    restart: unless-stopped
    hostname: main-app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db-app
      - rmq-app
    networks:
      - internet
      - appnet

  file-storage-app:
    build: ./apps/file-storage
    restart: unless-stopped
    hostname: file-storage-app
    env_file:
      - .env
    networks:
      - appnet

  db-app:
    image: postgres
    container_name: app-postgres
    restart: unless-stopped
    entrypoint:
      - 'POSTGRES_PASS='
    networks:
      - appnet

  rmq-app:
    image: rmq
    container_name: rmq-app
    hostname: rmq-app
    restart: unless-stopped
    networks:
      - appnet

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: internet
    driver: bridge
volumes:
  postgresql_data:
    driver: local