services:
  main-app:
    build:
      context: .
      dockerfile: ./apps/main-app/Dockerfile
      target: development
      command: yarn start:dev main-app
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - file-storage
    volumes:
    ports:
      - "3000:3000"
  file-storage:
    build:
      context: .
      dockerfile: ./apps/file-storage/Dockerfile
      target: development
      command: yarn start:dev file-storage
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
    ports:
      - "3001:3001"

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  postgres-user:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER_DB}

volumes: